### ISSUE TITLE
Week 1 - Task list and issues

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/world-energy-visualization#1]
**Set up repo**
- [x] License - Macy
- [x] Code of Conduct - Macy
- [x] Contribution guideline - Macy

**Team work contract**
- [x] Contract document - Mukund

**Proposal**
- [x] #3
- [x] Description of the data - Philson
- [x] #4

**App Description**
- [x] #8
- [x] #7
