### ISSUE TITLE
Week 2 - Task list and issues

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/world-energy-visualization#10]
**Deployment on Heroku**
- [x] Include the link on GitHub @MacyChan 
- [x] Procfile is using src.app:server @MacyChan 

**GitHub folder structure**
- [x] Put project proposal and reflections in doc folder @MacyChan 

**Interactive Dash app**
- [x] #11 @plevchen 
- [x] #12 @MacyChan 
- [x] #13 @miyer26 
- [x] #14 @PhilsChan 
* Make sure to have documentation of the plots

**Reflection (doc/reflection-milestone2.md)**
- [x] #19
- [ ] #15  @MacyChan @miyer26 @plevchen @PhilsChan 
- [ ] #16  @MacyChan @miyer26 @plevchen @PhilsChan 

**Improve the README**
_For people using your dashboard,_
- [x] table of contents @MacyChan 
- [x] Welcoming, About us @MacyChan 
- [x] The motivation behind your project @MacyChan 
- [x] what problem you are solving @MacyChan 
- [x] why it is important @MacyChan 
- [x] high level what they can do in your dashboard @plevchen 
- [x] short GIF of your dashboard @plevchen 

[reference](https://github.com/KirstieJane/STEMMRoleModels)

_For people helping you develop your dashboard,_

- [x] Potential contributors @PhilsChan 
- [x] how they can install your app and how to run it locally @PhilsChan 
- [x] Suggestions for what you would like help with and how to work in your project @PhilsChan
